### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [iamtreetop/SendPal#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
+ `requestId` needs to be snake_cased as these are backend routes.
+ You still have chirps in the patch route of the requests.

Thanks

**Comment by iamtreetop** [comment]
I made the change.  I would actually like to get your thoughts on this.   I have two ways in mind of handling the request/payment page.  Either with a modal(pop out) or new route pages.  Let me know what you think!

**Comment by linakherchi** [comment]
If you use the modal that is shared on FSP resources, it will be challenging to handle this request using a modal. Routes seem better and you can build that page to look like a modal with CSS.

Slack me if you want to meet and discuss it further!
